{"name": "test_resource_not_found", "status": "passed", "description": "Негативная проверка GET ресурс не найден", "steps": [{"name": "GET", "status": "passed", "start": 1685391411133, "stop": 1685391411396}], "attachments": [{"name": "stdout", "source": "482c53ab-2257-4731-8ddc-f97c116fc0f9-attachment.txt", "type": "text/plain"}], "start": 1685391411133, "stop": 1685391411396, "uuid": "9c61ebce-f77e-486b-a33e-459b8a90ae64", "historyId": "56a6688e8c64a9df13e8babdb4c4ef92", "testCaseId": "20b6bdf84171705c74ae1d4e074b4d1e", "fullName": "tests.test_reqres_api_negative.Test_negative_verification#test_resource_not_found", "labels": [{"name": "epic", "value": "Негативная проверка "}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_reqres_api_negative"}, {"name": "subSuite", "value": "Test_negative_verification"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "1600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_reqres_api_negative"}]}